# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: wilber_wallet_dev
  username: postgres
  password: postgres

test:
  <<: *default
  host: localhost
  database: wilber_wallet_test
  username: postgres
  password: postgres

# production:
#   <<: *default
#   host: localhost
#   database: wilber_wallet_prod
#   username: postgres
#   password: postgres

# staging: host: localhost
#   <<: *default
#   database: wilber_wallet_stg
#   username: postgres
#   password: postgres
